development:
  adapter: postgresql
  encoding: utf8
  encoding: utf8
  database: todo_dev_db
  pool: 5
  username: root
  password:

test:
  adapter: mysql
  encoding: utf8
  database: todo_dev_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: deng1cko6lf2v7
  username: mkhfluainuffuf
  password: qm1iI5xv05hkqevg359yHpawn3
